version: "3"
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: 
      - APP_ENV=${APP_ENV}
    ports:
      - 80:80
      - 443:443
    links:
      - backend
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs
    

  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - 5000:5000
    links:
      - database
    environment:
      - FLASK_ENV=${APP_ENV}
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend:/usr/src/app
  
  database:
    container_name: database
    restart: always
    image: mariadb/server:10.5
    ports:
      - 32000:3306
    environment: 
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes: 
      - ./database:/docker-entrypoint-initdb.d/:ro