name: Docker Compose deploy

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Go to deploy directory:
        run: cd src
      - name: Build the docker-compose stack
        run: sudo docker-compose --env-file .env.prod up --build
      - name: Check running containers
        run: docker ps -a
